### ISSUE TITLE
Also mind the `usb-tablet` driver

### ISSUE THREAD

**Issue by julian-r** [pmj/virtio-net-osx#8]
To have absolute mouse positioning without using the macos vnc: http://philjordan.eu/osx-virt/

**Comment by pmj** [comment]
Sorry, I'm not clear on what you're asking. What is your actual issue/request? I'm aware of the USB tablet driver (I wrote most of it) but I'm not sure how it relates to the virtio driver.

Thanks

**Comment by julian-r** [comment]
Sorry, wrong project, wanted to post it there: https://github.com/kholia/OSX-KVM

https://github.com/kholia/OSX-KVM/issues/33
